services:
  frontend:
    container_name: front-end
    image: frontend_random_image
    ports:
      - 8084:8084
    networks:
      - app-network
  backend:
    container_name: API
    image: api-random-image
    ports: 
      - 8082:8082
    networks:
      - app-network
networks:
  app-network:
    driver: bridge